### ISSUE TITLE
Keycloak 21.1 i18n Issue When Using Frontend URL

### ISSUE THREAD

**Issue by jspizziri** [keycloakify/keycloak-account-ui#4]
On Keycloak 21.1, when a "Frontend URL" is configured for a realm, i18n fails due to the fact that the `supportedLocales` object in the `kcContext` is empty.

I'm still looking into the cause as to why this would be the case, however if you have any insights that would be helpful.

Thanks!

**Comment by jspizziri** [comment]
A workaround for this is to enable "Internaltionalization" in your keycloak realm. By default, without internationalization enabled, keycloak enables English. For some reason, if you add a "Frontend URL" causes something in the sequence events to omit the default in `supportedLocales`.

**Comment by garronej** [comment]
Thank you for investigating.  
When kcContext.supportedLocales is empty, is kcContext.msgJSON empty as well?  

Because if it isn't it's an easy fix.

**Comment by jspizziri** [comment]
msgJSON is present unfortunately

**Comment by garronej** [comment]
no that's good, that means I can fix it very easyly

**Comment by garronej** [comment]
Hey @jspizziri, I released a new version, let me know if it fixes it!

**Comment by garronej** [comment]
And by the way I added support for extending i18n messages this moring: https://docs.keycloakify.dev/account-theme/single-page#i18n-internationalization-and-translation

**Comment by garronej** [comment]
Sorry I just fixed it, there was a type error preventing the release...
